#!/bin/sh -x
# SPDX-License-Identifier: MIT

export SMOKETEST_RESULT_DIR=/tmp/test-elos-smoketest
export ELOS_SCANNER_PATH=/usr/lib/elos/scanner
export SMOKETEST_DIR=/usr/lib/test/elos/smoketest/
export ELOS_BACKEND_PATH=/usr/lib/elos/backend
export ELOS_CLIENT_PATH=/usr/lib/elos/client

TEST_RUNNER="${SMOKETEST_DIR}/smoketest.sh"

$TEST_RUNNER
RET=$?

exit $RET
