#!/bin/sh -x
# SPDX-License-Identifier: MIT

export SMOKETEST_RESULT_DIR=/tmp/test-elos-smoketest
export ELOS_SYSLOG_PATH=/dev/log
export ELOS_KMSG_FILE=/dev/kmsg
export ELOS_SCANNER_PATH=/usr/lib/elos/scanner
export SMOKETEST_DIR=/usr/lib/test/elos-smoketest/
export ELOS_BACKEND_PATH=/usr/lib/elos/backend
export ELOS_CLIENT_PATH=/usr/lib/elos/client
export ELOS_COREDUMP_CONFIG_FILE=/etc/elos/coredump.json

TEST_RUNNER=/usr/lib/test/elos-smoketest/smoketest.sh

$TEST_RUNNER
RET=$?

exit $RET
