#!/bin/sh -x
# SPDX-License-Identifier: MIT

export SMOKETEST_RESULT_DIR=/tmp/test-samconf-integration


TEST_RUNNER=/usr/lib/test/samconf-integration/smoketest.sh


FAIL=0
RESULT=""
run_test() {
    TEST_NAME="${1}"
    RESULT="${RESULT}${TEST_NAME} "
    if time "${TEST_RUNNER}" "${TEST_NAME}" "${BUILD_TYPE}"; then
        RESULT="${RESULT} OK\n"
    else
        RESULT="${RESULT} FAILED\n"
        FAIL=$((FAIL + 1))
    fi
}

rm -rf "$SMOKETEST_RESULT_DIR"

run_test simple_config
run_test signed_config
run_test error_signed_config
run_test sign_config
run_test genkeys

echo "################################################################################"
echo "# Summary"
echo "################################################################################"
echo -e "${RESULT}"

exit "${FAIL}"
