# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""
PROJECT_LAYER_DIR ?= "${TOPDIR}/.."

BBLAYERS ?= " \
  ${PROJECT_LAYER_DIR}/meta-elos \
  ${PROJECT_LAYER_DIR}/poky/meta \
  ${PROJECT_LAYER_DIR}/poky/meta-poky \
  ${PROJECT_LAYER_DIR}/poky/meta-yocto-bsp \
  ${PROJECT_LAYER_DIR}/meta-openembedded/meta-oe/ \
  ${PROJECT_LAYER_DIR}/meta-openembedded/meta-python/ \
  ${PROJECT_LAYER_DIR}/meta-openembedded/meta-networking/ \
  "
